### ISSUE TITLE
PHP Fatal error:  Uncaught InvalidArgumentException: Router cache file must be a string or false

### ISSUE THREAD

**Issue by herrbischoff** [flextype/flextype#459]
### Environment

```
$ uname -a
FreeBSD vagrant 12.1-RELEASE FreeBSD 12.1-RELEASE r354233 GENERIC  amd64
```
```
$ php -v
PHP 7.4.8 (cli) (built: Aug  6 2020 01:30:04) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
```
```
$ php -m
[PHP Modules]
Core
ctype
date
dom
fileinfo
filter
gd
hash
iconv
json
libxml
mbstring
mysqlnd
pcre
PDO
pdo_sqlite
Phar
posix
Reflection
session
SimpleXML
SPL
sqlite3
standard
tokenizer
xml
xmlreader
xmlwriter
Zend OPcache
zip

[Zend Modules]
Zend OPcache
```
```
$ nginx -v
nginx version: nginx/1.18.0
```

### Issue

0. Unpacking https://github.com/flextype/flextype/releases/download/v0.9.9/flextype-cms-0.9.9.zip
1. Opening http://10.20.30.40/
2. Start of installation fails with a white screen. The request results in the following error (PHP error log):

```
[13-Aug-2020 19:50:09 UTC] PHP Fatal error:  Uncaught InvalidArgumentException: Router cache file must be a string or false in /usr/local/www/cockpit/vendor/slim/slim/Slim/Router.php:133
Stack trace:
#0 /usr/local/www/cockpit/vendor/slim/slim/Slim/DefaultServicesProvider.php(88): Slim\Router->setCacheFile()
#1 /usr/local/www/cockpit/vendor/pimple/pimple/src/Pimple/Container.php(118): Slim\DefaultServicesProvider->Slim\{closure}()
#2 /usr/local/www/cockpit/vendor/slim/slim/Slim/Container.php(109): Pimple\Container->offsetGet()
#3 /usr/local/www/cockpit/vendor/slim/slim/Slim/App.php(222): Slim\Container->get()
#4 /usr/local/www/cockpit/vendor/slim/slim/Slim/App.php(126): Slim\App->map()
#5 /usr/local/www/cockpit/src/flextype/app/Endpoints/entries.php(118): Slim\App->get()
#6 /usr/local/www/cockpit/src/flextype/bootstrap.php(75): include_once('/usr/local/www/...')
#7 /usr/local/www/cockpit/index.php(68): include('/usr/local/www/...')
#8 {main}
  thrown in /usr/local/www/cockpit/vendor/slim/slim/Slim/Router.php on line 133
```

I don't know what else to try. The application fails at init.

**Comment by Awilum** [comment]
https://docs.flextype.org/en/getting-started/requirements

Flextype is not tested on nginx yet, try with apache

**Comment by herrbischoff** [comment]
Thanks for the quick response. I'll be abandoning this evaluation then.
