### ISSUE TITLE
'Flextype\App\Foundation\Cache\ApcuCacheAdapter' not found Error

### ISSUE THREAD

**Issue by christiana83** [flextype/flextype#475]
Hi! 
Im trying to install flextype-cms-0.9.11 into a subfolder on a local system. Sub folder is set in htaccess RewriteBase. Following error occures: 

```
PHP Fatal error:  Uncaught Error: Class 'Flextype\App\Foundation\Cache\ApcuCacheAdapter' not found in /var/www/html/flextype-mp/src/flextype/dependencies.php:134
Stack trace:
#0 /var/www/html/flextype-mp/vendor/pimple/pimple/src/Pimple/Container.php(118): Flextype{closure}(Object(Slim\Container))
#1 /var/www/html/flextype-mp/src/flextype/app/Foundation/Flextype.php(66): Pimple\Container->offsetGet('cache_adapter')
#2 /var/www/html/flextype-mp/src/flextype/app/Support/Helpers/FlextypeHelper.php(23): Flextype\App\Foundation\Flextype->container('cache_adapter')
#3 /var/www/html/flextype-mp/src/flextype/app/Foundation/Cache/Cache.php(84): flextype('cache_adapter')
#4 /var/www/html/flextype-mp/src/flextype/app/Foundation/Cache/Cache.php(71): Flextype\App\Foundation\Cache\Cache->getCacheDriver()
#5 /var/www/html/flextype-mp/src/flextype/dependencies.php(141): Flextype\App\Foundation\Cache\Cache->__construct()
#6 /var/www/html/flextype-mp/vendor/pimple/pimple/src/Pimple/Container.php(118): Flextype{closure}(Object(Slim\Container))
 in /var/www/html/flextype-mp/src/flextype/dependencies.php on line 134

```
apcu modul is installed. 

I would be very thankful for any advice!

**Comment by christiana83** [comment]
I got the solution on discord.com from User Awilum:

```
@creative-sites try to use another cache driver, for e.g.  phparrayfile
https://docs.flextype.org/en/core/cache
Cache

go to project/config/flextype/settings.yaml and set cache driver - phparrayfile
cache:
  enabled: true
  driver: phparrayfile

APCU should be fixed in upcoming release
```
