### ISSUE TITLE
Fatal error: Uncaught Slim\Exception\HttpNotFoundException: 

### ISSUE THREAD

**Issue by Vegals** [flextype/flextype#593]
When I download Flextype and attempt to open it I receieve this error 

Fatal error: Uncaught Slim\Exception\HttpNotFoundException: Not found. in /Users/justinthomas/Herd/flextype/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php:76 Stack trace: #0 /Users/justinthomas/Herd/flextype/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(44): Slim\Middleware\RoutingMiddleware->performRouting(Object(Slim\Psr7\Request)) #1 /Users/justinthomas/Herd/flextype/vendor/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Middleware\RoutingMiddleware->process(Object(Slim\Psr7\Request), Object(Psr\Http\Server\RequestHandlerInterface@anonymous)) #2 /Users/justinthomas/Herd/flextype/src/flextype/core/Middlewares/WhoopsMiddleware.php(52): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(Slim\Psr7\Request)) #3 /Users/justinthomas/Herd/flextype/vendor/slim/slim/Slim/MiddlewareDispatcher.php(121): Flextype\Middlewares\WhoopsMiddleware->process(Object(Slim\Psr7\Request), Object(Psr\Http\Server\RequestHandlerInterface@anonymous)) #4 /Users/justinthomas/Herd/flextype/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(Slim\Psr7\Request)) #5 /Users/justinthomas/Herd/flextype/vendor/slim/slim/Slim/App.php(199): Slim\MiddlewareDispatcher->handle(Object(Slim\Psr7\Request)) #6 /Users/justinthomas/Herd/flextype/vendor/slim/slim/Slim/App.php(183): Slim\App->handle(Object(Slim\Psr7\Request)) #7 /Users/justinthomas/Herd/flextype/src/flextype/flextype.php(407): Slim\App->run() #8 /Users/justinthomas/Herd/flextype/index.php(46): require_once('/Users/justinth...') #9 /Applications/Herd.app/Contents/Resources/valet/server.php(153): require('/Users/justinth...') #10 {main} thrown in /Users/justinthomas/Herd/flextype/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php on line 76

I know am using Herd Laraval, would get the same error with XAMPP and MAMP. Running locally on a mac. 
Tried installing it to my host but it also just comes up blank. :/

**Comment by Bijoo** [comment]
PHP itself is itself somewhat of a framework, so using frameworks on frameworks ends up having unpredictable consequences.
